<a href="https://colab.research.google.com/github/RenukaD1998/internship/blob/master/internship4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="45px" src="https://colab.research.google.com/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Welcome to Colaboratory!</h1>


Colaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

With Colaboratory you can write and execute code, save and share your analyses, and access powerful computing resources, all for free from your browser.

In [0]:
#@title Introducing Colaboratory { display-mode: "form" }
#@markdown This 3-minute video gives an overview of the key features of Colaboratory:
from IPython.display import YouTubeVideo
YouTubeVideo('inN8seMm7UI', width=600, height=400)

## Getting Started

The document you are reading is a  [Jupyter notebook](https://jupyter.org/), hosted in Colaboratory. It is not a static page, but an interactive environment that lets you write and execute code in Python and other languages.

For example, here is a **code cell** with a short Python script that computes a value, stores it in a variable, and prints the result:

In [0]:
seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

86400

To execute the code in the above cell, select it with a click and then either press the play button to the left of the code, or use the keyboard shortcut "Command/Ctrl+Enter".

All cells modify the same global state, so variables that you define by executing a cell can be used in other cells:

In [0]:
seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

604800

For more information about working with Colaboratory notebooks, see [Overview of Colaboratory](/notebooks/basic_features_overview.ipynb).


## More Resources

Learn how to make the most of Python, Jupyter, Colaboratory, and related tools with these resources:

### Working with Notebooks in Colaboratory
- [Overview of Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Guide to Markdown](/notebooks/markdown_guide.ipynb)
- [Importing libraries and installing dependencies](/notebooks/snippets/importing_libraries.ipynb)
- [Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
- [Interactive forms](/notebooks/forms.ipynb)
- [Interactive widgets](/notebooks/widgets.ipynb)

### Working with Data
- [Loading data: Drive, Sheets, and Google Cloud Storage](/notebooks/io.ipynb) 
- [Charts: visualizing data](/notebooks/charts.ipynb)
- [Getting started with BigQuery](/notebooks/bigquery.ipynb)

### Machine Learning Crash Course
These are a few of the notebooks from Google's online Machine Learning course. See the [full course website](https://developers.google.com/machine-learning/crash-course/) for more.
- [Intro to Pandas](/notebooks/mlcc/intro_to_pandas.ipynb)
- [Tensorflow concepts](/notebooks/mlcc/tensorflow_programming_concepts.ipynb)
- [First steps with TensorFlow](/notebooks/mlcc/first_steps_with_tensor_flow.ipynb)
- [Intro to neural nets](/notebooks/mlcc/intro_to_neural_nets.ipynb)
- [Intro to sparse data and embeddings](/notebooks/mlcc/intro_to_sparse_data_and_embeddings.ipynb)

### Using Accelerated Hardware
- [TensorFlow with GPUs](/notebooks/gpu.ipynb)
- [TensorFlow with TPUs](/notebooks/tpu.ipynb)

## Machine Learning Examples: Seedbank

To see end-to-end examples of the interactive machine learning analyses that Colaboratory makes possible, check out the [Seedbank](https://research.google.com/seedbank/) project.

A few featured examples:

- [Neural Style Transfer](https://research.google.com/seedbank/seed/neural_style_transfer_with_tfkeras): Use deep learning to transfer style between images.
- [EZ NSynth](https://research.google.com/seedbank/seed/ez_nsynth): Synthesize audio with WaveNet auto-encoders.
- [Fashion MNIST with Keras and TPUs](https://research.google.com/seedbank/seed/fashion_mnist_with_keras_and_tpus): Classify fashion-related images with deep learning.
- [DeepDream](https://research.google.com/seedbank/seed/deepdream): Produce DeepDream images from your own photos.
- [Convolutional VAE](https://research.google.com/seedbank/seed/convolutional_vae): Create a generative model of handwritten digits.

In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
demoData = np.random.randint(10, 100, (10 ,2))
demoData

array([[63, 39],
       [62, 13],
       [87, 78],
       [71, 11],
       [18, 21],
       [39, 67],
       [93, 77],
       [85, 63],
       [43, 58],
       [74, 66]])

In [4]:
scalar_model = MinMaxScaler()
scalar_model.fit_transform(demoData)

array([[0.6       , 0.41791045],
       [0.58666667, 0.02985075],
       [0.92      , 1.        ],
       [0.70666667, 0.        ],
       [0.        , 0.14925373],
       [0.28      , 0.8358209 ],
       [1.        , 0.98507463],
       [0.89333333, 0.7761194 ],
       [0.33333333, 0.70149254],
       [0.74666667, 0.82089552]])

In [5]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
demoData = np.random.randint(1, 500, (20 ,4))
demoData

array([[493, 452,  58, 156],
       [ 25, 299,  23, 282],
       [180, 161,  64, 129],
       [425, 153, 474, 319],
       [251, 451, 287, 170],
       [468, 284, 166,  23],
       [  8, 435, 456, 315],
       [154, 328, 131,  66],
       [245, 135, 115, 225],
       [105, 206, 295, 168],
       [ 96, 168,  24, 289],
       [206, 411, 365, 222],
       [398, 263, 321, 330],
       [433, 393, 240, 487],
       [470, 237, 279, 249],
       [469,  88, 400, 385],
       [124, 255,  47, 316],
       [243, 444, 225, 168],
       [191, 195, 139, 332],
       [429, 170, 394, 405]])

In [6]:
scalar_model = MinMaxScaler()
feature_data = scalar_model.fit_transform(demoData)
feature_data

array([[1.        , 1.        , 0.07760532, 0.28663793],
       [0.03505155, 0.57967033, 0.        , 0.55818966],
       [0.35463918, 0.20054945, 0.09090909, 0.22844828],
       [0.85979381, 0.17857143, 1.        , 0.63793103],
       [0.50103093, 0.99725275, 0.58536585, 0.31681034],
       [0.94845361, 0.53846154, 0.31707317, 0.        ],
       [0.        , 0.9532967 , 0.96008869, 0.62931034],
       [0.30103093, 0.65934066, 0.23946785, 0.09267241],
       [0.48865979, 0.12912088, 0.20399113, 0.43534483],
       [0.2       , 0.32417582, 0.60310421, 0.3125    ],
       [0.1814433 , 0.21978022, 0.00221729, 0.57327586],
       [0.40824742, 0.88736264, 0.75831486, 0.42887931],
       [0.80412371, 0.48076923, 0.66075388, 0.66163793],
       [0.87628866, 0.83791209, 0.48115299, 1.        ],
       [0.95257732, 0.40934066, 0.56762749, 0.48706897],
       [0.95051546, 0.        , 0.83592018, 0.78017241],
       [0.23917526, 0.45879121, 0.05321508, 0.63146552],
       [0.48453608, 0.97802198,

In [7]:
import pandas as pd
df = pd.DataFrame(data=feature_data, columns=['k1', 'k2', 'k3', 'labels'])
df

k1        k2        k3    labels
0   1.000000  1.000000  0.077605  0.286638
1   0.035052  0.579670  0.000000  0.558190
2   0.354639  0.200549  0.090909  0.228448
3   0.859794  0.178571  1.000000  0.637931
4   0.501031  0.997253  0.585366  0.316810
5   0.948454  0.538462  0.317073  0.000000
6   0.000000  0.953297  0.960089  0.629310
7   0.301031  0.659341  0.239468  0.092672
8   0.488660  0.129121  0.203991  0.435345
9   0.200000  0.324176  0.603104  0.312500
10  0.181443  0.219780  0.002217  0.573276
11  0.408247  0.887363  0.758315  0.428879
12  0.804124  0.480769  0.660754  0.661638
13  0.876289  0.837912  0.481153  1.000000
14  0.952577  0.409341  0.567627  0.487069
15  0.950515  0.000000  0.835920  0.780172
16  0.239175  0.458791  0.053215  0.631466
17  0.484536  0.978022  0.447894  0.312500
18  0.377320  0.293956  0.257206  0.665948
19  0.868041  0.225275  0.822616  0.823276

In [12]:
X = df[['k1', 'k2', 'k3']]
y = df['labels']
X

k1        k2        k3
0   1.000000  1.000000  0.077605
1   0.035052  0.579670  0.000000
2   0.354639  0.200549  0.090909
3   0.859794  0.178571  1.000000
4   0.501031  0.997253  0.585366
5   0.948454  0.538462  0.317073
6   0.000000  0.953297  0.960089
7   0.301031  0.659341  0.239468
8   0.488660  0.129121  0.203991
9   0.200000  0.324176  0.603104
10  0.181443  0.219780  0.002217
11  0.408247  0.887363  0.758315
12  0.804124  0.480769  0.660754
13  0.876289  0.837912  0.481153
14  0.952577  0.409341  0.567627
15  0.950515  0.000000  0.835920
16  0.239175  0.458791  0.053215
17  0.484536  0.978022  0.447894
18  0.377320  0.293956  0.257206
19  0.868041  0.225275  0.822616

In [15]:
X = df[['k1', 'k2', 'k3']]
y = df['labels']
y

0     0.286638
1     0.558190
2     0.228448
3     0.637931
4     0.316810
5     0.000000
6     0.629310
7     0.092672
8     0.435345
9     0.312500
10    0.573276
11    0.428879
12    0.661638
13    1.000000
14    0.487069
15    0.780172
16    0.631466
17    0.312500
18    0.665948
19    0.823276
Name: labels, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
X_train.shape

(14, 3)